language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rake test
deploy:
  provider: heroku
  api_key:
    secure: GlOmwfNFWuH//FC7VsRTkz9yVEv8sIMFiFnrCpd34JsxRiwVptJHvATAN1vhMiCgLxCHSkJmalo5qWR4YNEzooU0UlwneU3xBrHeWJhY6kfvyf0EIjThZeQgfGZymAfy7tqgtx1umP5KQrdFmi5XdsdZFg8W+L8s517FajtPt3gXWymGTaEDX9TJMnXTJYn3jls/lyg/cnqOMQRzUwyH3hZATbV+Gu+wZFoTmur1RcMjhcTh+4cIse1PdCuVKyAynF8yHU1LhibwNda1i4/V+8Sk/FWclLn8yQ1gsWnu1PUrady4UOELWykfZg6U/ldfj3knkq/kZks014JinFPfEOOn2J+GEQQYTDFzMF/qTe+L2gYuYIa4H9SccnWuIi/BonCYM7vzBp2jvd/+i25SaGAFaqNmY6iIj2ADqA5Pkhpr4gjhefLLYWyv6RAbKMrUEOe25H9+RcbVTBNuhui+ZrUW9ddmUPNdEzdMWmHORTCv3kQM0C2U4NZRdIkmhekqAvjtl47cNQONRjYEjwJRb4SLDC2z138Q36RKWqhYBCZoniSXHx/jSyF13/daV/Z+RFtCCu94+1yEFSm3XNSrxBCXZcRny5nUAfJtGAMozbZfzxafOwybVo0+YQzbP95UZhcyn+JiiDvfN77M/0S2iNB+awPa7Ye7hCBdDXdAEZk=
  app: frozen-gorge-25653
  on:
    branch: main
    repo: vshaddix/Amitree-take-home-api
env:
  global:
    secure: kjeKrVysp8skDpQN29QeBnUSUibNiOxCFRPG7mJwLgpGIBzm2TJfaBhJSRhAG5jas2Fh1o5EiREexpx2i54/fx2MWgCs5oAH8rjpoPB23GsQE2bhQHwmfLCTkI/59VTqlb0KvLI4TnjIFzZ/DVi0B7O4P4GCggqsTKFUr3onfuNIVNpuxl9dc0r949DanljsRNXWWjGW0IruEqvVf6XTrE8DV7BySG8WSSvVGENmYMThTG1pwhgHIfvBhJZLIxaCkgS3Ixv2Jcgu1HP07Q/kc6CwbMJJKTLUX+rPTsRhuiKt9517vfYTq28eGyPNreTtQrFahtep4kNc52n85eUb4EeFNiXM1oJhylTaZoJg3/ArO6JZqGH3Fx1DtObevS39YdGKKlWZOGwcCCdxfGE5Bi2587464C74+L1o32QXUju4ShI29Yz0Q5gm1fl95Y44/FI0toI9gi6+myStQ/ld9cB0BoR051rsZwgAGzIC7QydFB9DUfkTbPXkBRjLQa3WdFzNbX/FaLE33gMtm2bYzU4DRVuJw+11zJDojEy/TTZQi0BzAav6nN2UcelqAY5i+t00/9wwuP5u1XAzs0N41/kHBvmI4DPV+/NDduDKNrZQk871ACO5vDisTA+5aEKNM5TnGjL4PZ2vglECxeBGivMTiuJb2VwTv84aDwowoD4=
